## Data Merge Template

In [1]:
import pandas as pd
import numpy as np

from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

In [3]:
url = 'https://github.com/mhall-simon/ESG-Investing/blob/main/test-data/Revenues_Formatted.xlsx?raw=true'

df = pd.read_excel(url, parse_dates = True, index_col = 0) # this sets index to the dates

df

,Year,Month and Day,Date,"Amazon.com, Inc. (NasdaqGS:AMZN) - Total Revenue","Church & Dwight Co., Inc. (NYSE:CHD) - Total Revenue","Chico's FAS, Inc. (NYSE:CHS) - Total Revenue",The Clorox Company (NYSE:CLX) - Total Revenue,"Autoliv, Inc. (NYSE:ALV) - Total Revenue","AutoZone, Inc. (NYSE:AZO) - Total Revenue","Coca-Cola FEMSA, S.A.B. de C.V. (NYSE:KOF) - Total Revenue",...,Lincoln Educational Services Corporation (NasdaqGS:LINC) - Total Revenue,"B&G Foods, Inc. (NYSE:BGS) - Total Revenue","Cracker Barrel Old Country Store, Inc. (NasdaqGS:CBRL) - Total Revenue",StoneMor Inc. (NYSE:STON) - Total Revenue,"Dine Brands Global, Inc. (NYSE:DIN) - Total Revenue","Grand Canyon Education, Inc. (NasdaqGS:LOPE) - Total Revenue",Zovio Inc (NasdaqGS:ZVO) - Total Revenue,"Spectrum Brands Holdings, Inc. (NYSE:SPB) - Total Revenue","Sequential Brands Group, Inc. (NasdaqCM:SQBG) - Total Revenue","Lumber Liquidators Holdings, Inc. (NYSE:LL) - Total Revenue"
Dates,,,,,,,,,,,,,,,,,,,,,
LTM1 2005,2005,-03-31,2005-03-31,7.293000e+09,1.586745e+09,NaN,NaN,6.349700e+09,NaN,4.871200e+10,...,272528000.0,3.721880e+08,NaN,91756000.0,352941000.0,NaN,NaN,4.918900e+07,NaN,NaN
LTM2 2005,2005,-06-30,2005-06-30,7.658000e+09,1.687775e+09,NaN,NaN,6.425700e+09,5.686007e+09,5.064800e+10,...,281558000.0,3.725690e+08,NaN,91344000.0,349705000.0,NaN,NaN,1.194740e+08,NaN,NaN
LTM3 2005,2005,-09-30,2005-09-30,8.054000e+09,1.710208e+09,NaN,4.319000e+09,6.434700e+09,5.664372e+09,5.193800e+10,...,290756000.0,3.729440e+08,2.515340e+09,95076000.0,354464000.0,NaN,NaN,1.093910e+08,NaN,NaN
LTM4 2005,2005,-12-31,2005-12-31,8.490000e+09,1.736506e+09,1.066882e+09,4.388000e+09,6.204900e+09,5.710882e+09,5.964200e+10,...,287368000.0,3.792620e+08,2.190866e+09,100660000.0,348023000.0,51793000.0,7951000.0,NaN,5803067.0,2.449470e+08
LTM1 2006,2006,-03-31,2006-03-31,8.867000e+09,1.758223e+09,1.137346e+09,4.444000e+09,6.079200e+09,5.762755e+09,5.600057e+10,...,303865000.0,3.821310e+08,2.490380e+09,106346000.0,350717000.0,NaN,NaN,-2.383100e+07,8698587.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
LTM2 2020,2020,-06-30,2020-06-30,3.217820e+11,4.593100e+09,2.050689e+09,6.133000e+09,7.112300e+09,1.207814e+10,1.889465e+11,...,285218000.0,1.927840e+09,2.814825e+09,285215000.0,720750000.0,819054000.0,400263000.0,3.786500e+09,91094000.0,1.067345e+09
LTM1 2021,2021,-03-31,2021-03-31,NaN,NaN,1.800411e+09,7.131000e+09,NaN,1.299319e+10,NaN,...,NaN,NaN,2.420206e+09,NaN,NaN,NaN,NaN,NaN,NaN,NaN
LTM3 2020,2020,-09-30,2020-09-30,3.479450e+11,4.744700e+09,2.035518e+09,6.365000e+09,7.121800e+09,1.207444e+10,1.869820e+11,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
LTM3 2021,2021,-09-30,2021-09-30,NaN,NaN,1.464939e+09,NaN,NaN,NaN,NaN,...,NaN,NaN,2.522792e+09,NaN,NaN,NaN,NaN,3.964200e+09,NaN,NaN
LTM2 2021,2021,-06-30,2021-06-30,NaN,NaN,1.598229e+09,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
company_name = []
exchange = []
ticker = []


for equity in df.columns:
    beg = equity.find("(")
    end = equity.find(")")
    
#     equity[beg+1:end] # can use the subset notation to select parts of a string
    
    company_name.append(equity[:beg-1])
    
    exchange.append(equity[beg+1:end].split(":")[0])
    ticker.append(equity[beg+1:end].split(":")[1])

IndexError: list index out of range

In [4]:
df.columns = ticker
df

               MO      BRFS3   FEMSA UBD  ...      YUM     PM    WBA
Dates                                     ...
2004-02-29  57.55   4.666666   16.556666  ...   18.515    NaN  35.66
2004-03-31  54.45   5.000000   18.323333  ...   18.995    NaN  32.95
2004-04-30  55.38   4.750000   16.566666  ...   19.395    NaN  34.48
2004-05-31  47.97   4.500000   16.273332  ...   18.750    NaN  35.01
2004-06-30  50.05   4.500000   17.573332  ...   18.610    NaN  36.21
...           ...        ...         ...  ...      ...    ...    ...
2020-10-31  36.08  16.780000  113.690000  ...   93.330  71.02  34.04
2020-11-30  39.83  22.030000  145.950000  ...  105.800  75.75  38.01
2020-12-31  41.00  22.040000  150.340000  ...  108.560  82.79  39.88
2021-01-31  41.08  21.220000  139.700000  ...  101.490  79.65  50.25
2021-02-28  43.60  21.640000  143.140000  ...  103.530  84.02  47.93

[205 rows x 49 columns]

In [5]:
master = pd.DataFrame(columns={'Dates', 'Ticker'}) # creates an empty multi-index master file
master = master.set_index(['Dates', 'Ticker'])

In [6]:
for col in df.columns:
    idx = pd.MultiIndex.from_product([df.index, [col]], names = ['Dates', 'Ticker'])
    data = pd.DataFrame(df.loc[:,col].values, index = idx)
    data = data.rename(columns={0:"Revenue"})
    data.dropna(inplace=True)

    master = master.append(data)

In [7]:
master

                   Price         R
Dates      Ticker
2004-03-31 MO      54.45 -0.053866
2004-04-30 MO      55.38  0.017080
2004-05-31 MO      47.97 -0.133803
2004-06-30 MO      50.05  0.043360
2004-07-31 MO      47.60 -0.048951
...                  ...       ...
2020-10-31 WBA     34.04 -0.052339
2020-11-30 WBA     38.01  0.116627
2020-12-31 WBA     39.88  0.049198
2021-01-31 WBA     50.25  0.260030
2021-02-28 WBA     47.93 -0.046169

[9937 rows x 2 columns]

In [8]:
master = master.sort_index(level=0, ascending=True, sort_remaining=True) # sort_remaining says it'll sort by ticker second
master

                     Price         R
Dates      Ticker
2004-03-31 6758    4360.00 -0.022422
           7203    3880.00  0.029178
           7267    2400.00  0.008403
           ABI       22.39 -0.074793
           ADM       16.87 -0.019186
...                    ...       ...
2021-02-28 TPR       42.14  0.332701
           ULVR      37.33 -0.119575
           WBA       47.93 -0.046169
           WMT      129.92 -0.075237
           YUM      103.53  0.020101

[9937 rows x 2 columns]